import { DataTypes, QueryTypes } from "sequelize";
import sequelize from "../mysql/connection.js";

const EmployeesModel = sequelize.define(
  "employees",
  {
    id: { type: DataTypes.BIGINT.UNSIGNED, primaryKey: true, autoIncrement: true },
    emp_no: { type: DataTypes.STRING(250), allowNull: true },
    employee_bio_id: { type: DataTypes.STRING(250), allowNull: true },
    religion_id: { type: DataTypes.BIGINT, allowNull: true },
    employee_id: { type: DataTypes.STRING(250), allowNull: true },
    access_control_code: { type: DataTypes.STRING(250), allowNull: true },
    reporting_manager_id: { type: DataTypes.BIGINT, allowNull: false, defaultValue: 0 },
    user_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: false },
    name: { type: DataTypes.STRING(255), allowNull: false },
    arabic_name: { type: DataTypes.STRING(255), allowNull: true },
    arabic_first_name: { type: DataTypes.STRING(255), allowNull: true },
    arabic_middle_name: { type: DataTypes.STRING(255), allowNull: true },
    arabic_last_name: { type: DataTypes.STRING(255), allowNull: true },
    slug: { type: DataTypes.STRING(255), allowNull: false },
    first_name: { type: DataTypes.STRING(100), allowNull: false },
    middle_name: { type: DataTypes.STRING(100), allowNull: true },
    last_name: { type: DataTypes.STRING(100), allowNull: true },
    gender: { type: DataTypes.ENUM('Male', 'Female', 'Not to Answer'), allowNull: false, defaultValue: 'Not to Answer' },
    email: { type: DataTypes.STRING(255), allowNull: true },
    image: { type: DataTypes.STRING(255), allowNull: true, defaultValue: 'no_image.png' },
    phone: { type: DataTypes.STRING(20), allowNull: true },
    dob: { type: DataTypes.DATEONLY, allowNull: true },
    allowed_holiday: { type: DataTypes.INTEGER, allowNull: true },
    country_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    city_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    passport_no: { type: DataTypes.STRING(100), allowNull: true },
    qid_visa_no: { type: DataTypes.STRING(100), allowNull: true },
    qid_visa_type: { type: DataTypes.ENUM('VISA', 'QID'), allowNull: true, defaultValue: 'QID' },
    marital_status: { type: DataTypes.ENUM('Single Never Married', 'Married', 'Divorced', 'Widowed'), allowNull: true },
    address: { type: DataTypes.TEXT, allowNull: true },
    sponsor_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true, defaultValue: 0 },
    accommodation_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    workplace_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    department_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    position_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    joining_date: { type: DataTypes.DATEONLY, allowNull: true },
    contract_sign_date: { type: DataTypes.DATEONLY, allowNull: true },
    salary_group_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    role_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    days_off_count: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, defaultValue: 0 },
    temporary_staff: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'No' },
    exceptional_staff: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'No' },
    non_compete_clause: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'Yes' },
    non_compete_clause_value: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 30000.00 },
    non_disclosure_clause: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'Yes' },
    non_disclosure_clause_value: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 50000.00 },
    basic_hourly_salary: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    basic_daily_salary: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    basic_salary: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    transportation: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    food_allowances: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    other_allowances: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    house_allowances: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    air_ticket_allowance_cycle: { type: DataTypes.ENUM('Every Two Year', 'Every One Year'), allowNull: false, defaultValue: 'Every Two Year' },
    have_accommodation: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'No' },
    total_salary: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    total_salary_hourly: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    total_salary_daily: { type: DataTypes.DECIMAL(20, 2), allowNull: false, defaultValue: 0.00 },
    contract_type: { type: DataTypes.ENUM('Full Time', 'Part Time', 'Inter', 'Probation', 'Not Selected'), allowNull: false, defaultValue: 'Not Selected' },
    probation_months: { type: DataTypes.ENUM('No Probation', '3 Months', '6 Months'), allowNull: false, defaultValue: 'No Probation' },
    hire_type: { type: DataTypes.ENUM('Local', 'International', 'OutSource'), allowNull: false, defaultValue: 'Local' },
    salary_paid_by: { type: DataTypes.ENUM('Bank', 'Cash', 'Personal or Other'), allowNull: false, defaultValue: 'Bank' },
    qid_visa_doc: { type: DataTypes.STRING(250), allowNull: true },
    education_level: { type: DataTypes.STRING(250), allowNull: true },
    years_of_experience: { type: DataTypes.STRING(250), allowNull: true },
    qid_visa_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    signature: { type: DataTypes.STRING(250), allowNull: true },
    signature_base64: { type: DataTypes.TEXT, allowNull: true },
    signed_contact_doc: { type: DataTypes.STRING(250), allowNull: true },
    previous_sponsor_doc: { type: DataTypes.STRING(250), allowNull: true },
    passport_doc: { type: DataTypes.STRING(250), allowNull: true },
    passport_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    health_insurance_doc: { type: DataTypes.STRING(250), allowNull: true },
    health_insurance_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    health_cert_doc: { type: DataTypes.STRING(250), allowNull: true },
    health_cert_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    food_handling_certificate_doc: { type: DataTypes.STRING(250), allowNull: true },
    food_handling_certificate_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    labour_contract_doc: { type: DataTypes.STRING(250), allowNull: true },
    labour_contract_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    internal_contract_doc: { type: DataTypes.STRING(250), allowNull: true },
    internal_contract_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    part_time_contract_doc: { type: DataTypes.STRING(250), allowNull: true },
    part_time_contract_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    mutual_confidentially_agreement_doc: { type: DataTypes.STRING(250), allowNull: true },
    mutual_confidentially_agreement_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    education_certificates_doc: { type: DataTypes.STRING(250), allowNull: true },
    drivers_license_doc: { type: DataTypes.STRING(250), allowNull: true },
    drivers_license_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    work_auth_doc: { type: DataTypes.STRING(250), allowNull: true },
    work_auth_expiry: { type: DataTypes.DATEONLY, allowNull: true },
    bank_id: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    bank_account_name: { type: DataTypes.STRING(250), allowNull: true },
    bank_iban: { type: DataTypes.STRING(250), allowNull: true },
    bank_branch: { type: DataTypes.STRING(250), allowNull: true },
    bank_card_no: { type: DataTypes.STRING(250), allowNull: true },
    bank_pin_code: { type: DataTypes.STRING(250), allowNull: true },
    status: { type: DataTypes.ENUM('Active', 'Deactive'), allowNull: false, defaultValue: 'Deactive' },
    is_terminated: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'No' },
    is_resign: { type: DataTypes.ENUM('Yes', 'No'), allowNull: false, defaultValue: 'No' },
    created_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    updated_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    deleted_by: { type: DataTypes.BIGINT.UNSIGNED, allowNull: true },
    deleted_at: { type: DataTypes.DATE, allowNull: true },
    created_at: { type: DataTypes.DATE, allowNull: true, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, allowNull: true, defaultValue: DataTypes.NOW },
  },
  {
    timestamps: false,
    tableName: "employees",
  }
);

export default EmployeesModel;
